# This workflow file build the Godot project for multiple target systems.
---


# Build workflow
name: Build


# Trigger rules (adjust to configure when CI is performed)
on:
  [push, pull_request]


# Environment variables
env:
  # Configure Godot version
  GODOT_VERSION: 4.2.1

  
  # # Butler API Key (comment to disable)
  # BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  
  # # Butler User/Game (set to itch.io user/game)
  # BUTLER_USER_GAME: malcolmnixon/godotcibuilddemo


# CI jobs
jobs:
  # Build job (Matrix build for all exports)
  build:
    name: Building for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        include:
          # Export for Windows
          - name: 🏁 Windows
            os: windows-latest
            platform: windows
            export-preset: windows
            export-type: release
            export-folder: build/windows
            archive: Windows
            butler-channel: windows

          # Export for Linux
          - name: 🐧 Linux
            os: ubuntu-22.04
            platform: linux
            export-preset: linux
            export-type: release
            export-folder: build/linux
            archive: Linux
            butler-channel: linux

    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Ensure submodules are checked out if used
          submodules: 'true'
          # Specify the repository and branch if necessary
          repository: 'unibuc-cs/software-engineering-product-bcc'
          # ref: 'main'  # or the specific branch you're targeting

      # Setup Godot
      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: ${{ env.GODOT_VERSION }}
          use-dotnet: false
          include-templates: true

      # Import Godot Project
      - name: Initial Godot Import
        shell: bash
        run: |
          godot --headless --import || exit 0

      # Export project
      - name: Export Godot Project
        shell: bash
        run: >
          godot
          --headless
          ${{ matrix.export-args }}
          --export-${{ matrix.export-type }} "${{ matrix.export-preset }}"

      # Upload artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.archive }}-Artifacts
          path: |
            ${{ matrix.export-folder }}/*.*
            !**/.gitignore

      # Install butler (if building release with butler support)
      - name: Install Butler
        if: >
          github.event_name == 'push' && 
          github.ref_type == 'tag' &&
          env.BUTLER_API_KEY != ''
        uses: remarkablegames/setup-butler@v1
        with:
          butler-version: LATEST

      # Push to itch.io (if building release)
      - name: Push to itch.io
        if: >
          github.event_name == 'push' && 
          github.ref_type == 'tag' &&
          env.BUTLER_API_KEY != ''
        run: >
          butler push
          --ignore '.gitignore'
          ${{ matrix.export-folder }}
          ${{ env.BUTLER_USER_GAME }}:${{ matrix.butler-channel }}
          --userversion ${{ github.ref_name }}

      # Compress project (if building release)
      - name: Compress Project
        if: >
          github.event_name == 'push' && 
          github.ref_type == 'tag'
        run: |
          cd ${{ matrix.export-folder }}
          7z a -tzip ${{ matrix.archive }}.zip *.* -x'!.gitignore'

      # Publish release (if building release)
      - name: Publish Release
        uses: ncipollo/release-action@v1
        if: >
          github.event_name == 'push' && 
          github.ref_type == 'tag'
        with:
          allowUpdates: true
          artifacts: '${{ matrix.export-folder }}/${{ matrix.archive }}.zip'
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}
